### ISSUE TITLE
大佬，克隆到本地运行直接报错了呀

### ISSUE THREAD

**Issue by 1229984599** [tolking/element-admin-template#15]
![image](https://user-images.githubusercontent.com/34052312/172414888-2984d6d5-9445-4779-a27e-8716dccb9eb1.png)

**Comment by tolking** [comment]
如果你 `unplugin-auto-import` 版本在 0.8.x 可能需要

// vite.config.ts
```diff
AutoImport({
+ vueTemplate: true,
imports: ['vue', 'vue-router', '@vueuse/core', customImports],
```

**Comment by 1229984599** [comment]
> 如果你 `unplugin-auto-import` 版本在 0.8.x 可能需要
> 
> // vite.config.ts
> 
> ```diff
> AutoImport({
> + vueTemplate: true,
> imports: ['vue', 'vue-router', '@vueuse/core', customImports],
> ```

大佬，按照您这样加了还是不行呀，而且我是直接克隆的你的代码，没有任何修改，在控制台里面还是在报这种错
![image](https://user-images.githubusercontent.com/34052312/172509833-6d2a22df-9ac4-44fc-bc41-34e575a55c64.png)

**Comment by tolking** [comment]
我无法复制你的错误。请查看是否是克隆最新的 1.1.3 版本

或者很可能是存在部分依赖安装错误，

- 升级所有依赖到最新版本
- 最好使用 pnpm / yarn 替代 npm，同时注意安装依赖是否提示错误
- 最好使用 npm 而不是 taobao npm 作为安装源

**Comment by tolking** [comment]
我仔细想了一下，可能和和 unplugin-auto-import 与 unplugin-vue-components 相关。项目目前不能够和这俩完美结合，正在计划移除。你可以选择手动移除。或者期待即将更新的版本。
