### ISSUE TITLE
例子还是太少了,我有空时可以pr上去吗

### ISSUE THREAD

**Issue by InfernalAzazel** [tolking/element-admin-template#32]
比如 任务表格 监控任务状态 等等
刚好 最近在写 类似这个需求项目

定时任务 或者 任务调度 类项目需要用的

或者作者有空搞上去也行.

类似参考 这种表格
https://preview.pro.ant.design/list/table-list
https://preview.pro.antdv.com/list/basic-list

**Comment by tolking** [comment]
欢迎

**Comment by InfernalAzazel** [comment]
> 欢迎

是时候了解因果了.

**Comment by InfernalAzazel** [comment]
> > 欢迎
> 
> 是时候了解因果了,太忙了写一个类似我现在现在项目跑的任务表格.
