### ISSUE TITLE
useCrud 请求有一定可能导致表格没有刷新新增数据

### ISSUE THREAD

**Issue by InfernalAzazel** [tolking/element-admin-template#33]
https://github.com/tolking/element-admin-template/blob/main/src/composables/crud.ts

原理: 前端在添加数据时,数据提交给后端,然而后端在没有插入数据库前,前端就使用了 loadList() 进行查询, 导致添加后的数据没有展示出来

解决方法, 预估后端处理时间给出相应延迟

```
 setTimeout(async () => {
                await loadList()
            }, 500)
```

**Comment by tolking** [comment]
后端不是应该在插入数据库后返回状态吗？不是怎么能够确定增加数据是否成功

**Comment by InfernalAzazel** [comment]
> 后端不是应该在插入数据库后返回状态吗？不是怎么能够确定增加数据是否成功

后端是需要执行业务的时间的, add 进行处理业务, list 查询业务数据, add 在执行业务逻辑时,但没有插入数据库前,你去查询是不是没有查询数据..

**Comment by InfernalAzazel** [comment]
![Screenshot from 2022-11-22 09-48-21](https://user-images.githubusercontent.com/40333954/203197026-6066dffe-37cc-4e6b-822e-ae39863fd983.png)
我这边add 还是调用 后台任务耗时会比较久, 所以说直接查询确实的会存在我这个问题的, 查询速度 比如插入速度快就会.
之前我一直以为是 组件bug后面分析到原因.

**Comment by tolking** [comment]
这属于你自己业务问题。

就算增加500毫秒，你这样依然可能出现问题
