### ISSUE TITLE
[bug] 头像下拉鼠标指向时出现黑色选中框 

### ISSUE THREAD

**Issue by InfernalAzazel** [tolking/element-admin-template#36]
### 复现

https://github.com/tolking/element-admin-template/blob/main/src/layout/Layout.vue

### 效果
![2023-07-10_10-44](https://github.com/tolking/element-admin-template/assets/40333954/025cda8d-d0e1-4b36-8c0b-01a92d1bce93)

![2023-07-10_10-45](https://github.com/tolking/element-admin-template/assets/40333954/37d769c7-d6ea-4a60-9074-d5ea95421716)

### 这个bug 的出现

升级到 vite 3.9，下拉框就出现这种情况了，怀疑2个可能性问题。

- 注 vite 2.8 没有这种情况

1. element-plus 没有适配 vite 3.9
2. element-pro-components 没有适配 vite 3.9

**Comment by tolking** [comment]
是不是你的图片挂了

**Comment by InfernalAzazel** [comment]
> 是不是你的图片挂了

1. 不太可能，因为这个几天前就会了，我反复确认过，也尝试解决问题，实在解决不了。
2. 上面官方代码我是拉去最新下来跑的。

**Comment by tolking** [comment]
黑色的边框是默认的focus样式，不需要可以自行隐藏。这属于A11y标准

**Comment by InfernalAzazel** [comment]
> 黑色的边框是默认的focus样式，不需要可以自行隐藏。这属于A11y标准

厉害
